---

- name: "Install scorpiobroker service on OpenShift"
  k8s:
    state: present
    definition: "{{ lookup('template', 'service-scorpiobroker.yaml') }}"
- name: "Install scorpiobroker deployment on OpenShift"
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment-scorpiobroker.yaml') }}"
