apiVersion: v1
kind: Service
metadata:
  name: scorpiobroker
  namespace: "{{ SCORPIOBROKER_NAMESPACE }}"
  labels:
    app.kubernetes.io/instance: scorpiobroker
    app.kubernetes.io/name: scorpiobroker
spec:
  ports:
    - name: http
      port: {{ SCORPIOBROKER_PORT }}
      protocol: TCP
      targetPort: {{ SCORPIOBROKER_PORT }}
  selector:
    app.kubernetes.io/instance: scorpiobroker
    app.kubernetes.io/name: scorpiobroker
  type: ClusterIP
